apiVersion: v1
kind: Service
metadata:
  name: ecom-web-service
spec:
  selector:
    app: ecom-web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000
  type: NodePort
